apiVersion: v1
kind: PersistentVolume # Create a PV
metadata:
  name: postgresql-data1 # Sets PV's name
  labels:
    type: local # Sets PV's type to local
  namespace: postgresql1
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi # Sets PV Volume
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/eliot/projects/HEIR/code/postgres/dataK8s" # Sets the volume's path
