apiVersion: katalog.fybrik.io/v1alpha1
kind: Asset
metadata:
  name: observation-json
  namespace: fybrik-system
spec:
  details:
    connection:
      fhir:
        fhirServer: https://fhir-sandbox.heirproject.eu/fhir-server/api/v4/
        namespace: fybrik-system
        port: 9443
        secretRef: fhir-credentials
      name: fhir
    dataFormat: json
  metadata:
    columns:
    - name: id
      tags:
        PII: true
    - name: reference
      tags:
        PII: true
    geography: UK
    name: observation
    tags:
      observation: true
  secretRef:
    name: fhir-credentials
