kind: ValidatingWebhookConfiguration
apiVersion: admissionregistration.k8s.io/v1beta1
metadata:
  name: opa-validating-webhook
webhooks:
  - name: validating-webhook.openpolicyagent.org
    namespaceSelector:
      matchExpressions:
      - key: openpolicyagent.org/webhook
        operator: NotIn
        values:
        - ignore
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["*"]
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNyRENDQVpRQ0NRRFdJM0NKMjYyZDJqQU5CZ2txaGtpRzl3MEJBUXNGQURBWE1SVXdFd1lEVlFRRERBeGgKWkcxcGMzTnBiMjVmWTJFd0lCY05Nak13TkRJM01Ea3pNelV5V2hnUE1qSTVOekF5TURrd09UTXpOVEphTUJjeApGVEFUQmdOVkJBTU1ER0ZrYldsemMybHZibDlqWVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDCkFRb0NnZ0VCQU8xcjNwdUR4ZFFMZWFCM0VTTmpXNDV3dnhnZkpsUXd3N0ZQbzhiazJNV1pQUHRhbkhUZHdmMlYKUzhsRCtVVjdUcEhUbUJNZGdqU2x3cC9rZjhNVlhmZStxcmh2UGRmTDBEWUU5N2t0QkxMV0hHZmNrTmJ4VHZhYQpYY0F0SW9xZDVsRlo0ZzNDdEFzUHBEZksyUEQzcGN6NGFUNWZPSlJwYk5vTzRjL1VhYjJJc1ZZcWs4UStFTE53CkZsNjFVakxzSm45M3dKekd0UmZZaG84c3hpbVQvNGtFQUVHa29VVEt0Rk9hSXYva2RETWgzaGIzSFNKSVBuZlgKZDFaMkQ2OHJXdU0wRTMxU2FxZDZNWGZnaGFMWUhheE50NW1Va0RLUlovMk1vMjNGaUw2RDNLWHdhRjVndS9UVgptMnR5MlJteU1vYS9PcStBeG9OUzJZMmp3UzVyeVhrQ0F3RUFBVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBCnBlelp3aU55YUpncW5Bbzkwc01WVUZjSHpRV1REQkJXNHdtYkRLMmFEWHVaVlVtSXVqalRpWjVCOEk4UlZaZnMKeEpjZlB0U3pubE1WRVhWdUxsWXpSQVdpSFppcVlJSU1mdlJwL2xxMHp5SkxvR2drV3E1RHpSY3k3cEU1NExRcwpPUS9JK2lHV3M0SUloaFk4SXRmQ0hQT2cwNzZxeUdVVHNaM1Z3TGo2anVMTUVQMHl1dEhyQ2NlVEdKQ3NKc2pyCnpGcFlYWWd5bXpVMDR3UmFwdmNTYUlQT29XNWRNUDV3K0t6N01uQ2kyaWxoOGVVMFZ6K1NtRFVLT2dDSlNHdHoKakUwT1FmSkNYVWhFMjFRblhVWkwrRHJxanRoLzR1cGRzNGI3V3RFWW9YRVdIYzJUYlc0bHlzWFhyR0R6aG5lSQozaXRiMm1PQ0xYNTBYcDFZSXFZc2V3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      service:
        namespace: opa
        name: opa
